import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Button from '../comps/Button/Button'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>An investment in knowledge pays the best interest.</h1>
          <hr className={styles.line} />
          <p>
            Different than a college or university, the British Columbia Institute of Technology offers practical, flexible, applied education with instructors who have direct, hands-on experience in their field.
          </p>
        </div>
        <div className={styles.btncont}>
          <Button text='More About Us'></Button>
          <Button text='Contact Us' />
        </div>
      </main>
    </>
  )
}
